version: "3.8"
services:
  web:
    build: .
    env_file:
      - .env
    ports:
      - "5000:5000"
#    command:
#      python app.py
  worker:
    build: .
    env_file:
      - .env
#    command:
#      python run_worker.py
